# Generated by Django 4.2.1 on 2023-05-14 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_alter_account_registrationdate"),
    ]

    operations = [
        migrations.CreateModel(
            name="SearchHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.CharField(max_length=100)),
                ("query", models.CharField(max_length=200)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="UsersMusic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="musiclist",
            name="albumImageURL",
            field=models.CharField(default="", max_length=1000),
        ),
        migrations.AlterField(
            model_name="account",
            name="email",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="musiclist",
            name="id",
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
